struct WrittenKnowledgeAcquisition {
    let claimID: AgentKnowledgeClaimID
    let claimEventID: AgentCausalEventID
    let belief: AgentKnowledgeBelief
    let proposition: AgentKnowledgeProposition
    let authorityID: AgentKnowledgeHistoricalBeliefAuthorityID
}

extension AgentSimulationSession {
    func writtenClaimID(_ readingID: String, readerID: AgentID) -> AgentKnowledgeClaimID {
        AgentKnowledgeClaimID(rawValue: "claim-" + AgentKnowledgeDigest.make(
            "written|\(readerID.rawValue)|\(readingID)"))!
    }

    /// CIV-41's existing understanding/revision owners process the claim. No
    /// direct evidence or World fact is generated by reading material text.
    mutating func acquireWrittenSourceClaim(artifact: AgentWrittenArtifact,
        readingID: String, readerID: AgentID,
        readingEventID: AgentCausalEventID) throws -> WrittenKnowledgeAcquisition {
        guard var knowledge = knowledgeGraphState, knowledge.enabled,
              let source = knowledge.historicalBeliefAuthorities?.first(where: {
                $0.authorityID == artifact.sourceAuthorityID
              }) else { throw AgentWritingError.unavailable("historical written source") }
        guard source.ownerID == artifact.plan.authorID else {
            throw AgentWritingError.invalidState("written source owner")
        }
        let proposition = artifact.plan.assertedProposition
        insertKnowledgeProposition(proposition, into: &knowledge)
        let claimID = writtenClaimID(readingID, readerID: readerID)
        guard !knowledge.claims.contains(where: { $0.claimID == claimID }) else {
            throw AgentWritingError.invalidState("duplicate written claim")
        }
        let event = try requiredKnowledgeEvent(kind: .knowledgeClaimReceived,
            actorID: artifact.plan.authorID, subjectID: readerID, causes: [readingEventID],
            recordID: claimID.rawValue, propositionID: proposition.propositionID,
            status: "attributedWrittenSourceClaim", reason: readingID,
            summary: "knowledge acquired from local inscription")
        var claim = AgentKnowledgeSourceClaim(claimID: claimID,
            propositionID: proposition.propositionID, sourceAgentID: artifact.plan.authorID,
            recipientID: readerID, sourceEvidenceID: nil, socialMessageID: nil,
            sourceBeliefAuthorityID: artifact.sourceAuthorityID,
            languageCommunicationID: nil, oralTransmissionID: nil,
            sentEventID: artifact.inscriptionEventID, receivedEventID: readingEventID,
            acquisitionEventID: event.eventID, receivedAtTick: tick)
        claim.writtenSource = AgentKnowledgeWrittenSource(
            artifactID: artifact.artifactID, readingID: readingID)
        knowledge.claims.append(claim)
        let understanding = try formKnowledgeUnderstanding(ownerID: readerID,
            proposition: proposition, basis: .sourceClaim(claimID),
            interpretation: .acceptedAsAsserted, cause: event.eventID, state: &knowledge)
        try reviseKnowledgeBelief(ownerID: readerID, proposition: proposition,
            stance: .accepted, understanding: understanding, state: &knowledge)
        try compactKnowledgeState(&knowledge)
        guard let belief = knowledge.beliefs.first(where: {
            $0.ownerID == readerID && $0.basisUnderstandingID == understanding.understandingID
        }) else { throw AgentWritingError.invalidState("written belief publication") }
        knowledgeGraphState = knowledge
        let digest = knowledgeHistoricalBeliefAuthorityDigest(beliefID: belief.beliefID,
            ownerID: readerID, proposition: proposition, stance: belief.stance,
            basisUnderstandingID: belief.basisUnderstandingID,
            beliefFormedAtTick: belief.formedAtTick, beliefUpdatedAtTick: belief.updatedAtTick,
            beliefRevisionCount: belief.revisionCount, sourceBeliefRevisionEventID: belief.lastRevisionEventID)
        return WrittenKnowledgeAcquisition(claimID: claimID, claimEventID: event.eventID,
            belief: belief, proposition: proposition,
            authorityID: AgentKnowledgeHistoricalBeliefAuthorityID(rawValue: "historical-belief-authority-" + digest)!)
    }

    func validWrittenKnowledgeClaim(_ claim: AgentKnowledgeSourceClaim) -> Bool {
        guard let reference = claim.writtenSource,
              claim.sourceEvidenceID == nil, claim.socialMessageID == nil,
              claim.languageCommunicationID == nil, claim.oralTransmissionID == nil,
              let artifact = writingState?.artifacts.first(where: { $0.artifactID == reference.artifactID }),
              let reading = writingState?.readings.first(where: { $0.readingID == reference.readingID }),
              reading.artifactID == artifact.artifactID,
              reading.readerID == claim.recipientID, reading.claimID == claim.claimID,
              artifact.plan.authorID == claim.sourceAgentID,
              artifact.sourceAuthorityID == claim.sourceBeliefAuthorityID,
              artifact.plan.realization.semanticContent.sourcePropositionID == claim.propositionID,
              artifact.inscriptionEventID == claim.sentEventID,
              reading.readingEventID == claim.receivedEventID,
              reading.claimEventID == claim.acquisitionEventID,
              reading.physicalReceipt.observedAtTick == claim.receivedAtTick else { return false }
        return true
    }
}
